/* The sketchbook: a hand of cards you deal onto a table, and the catalogue.
   ---------------------------------------------------------------------------
   Classic script, no imports, no build step — the same shape as site.js and
   skeleton.js, because these pages are plain HTML that works from any static
   server and the day one of them needs a bundler to run is the day it stops
   being that.

   The works come from assets/sketchbook/works.json, which was generated by a
   one-pass scrape of the live Framer sketchbook (its provenance is recorded in
   the file itself). Reading it rather than writing a hundred <img> tags by hand
   is the point: the catalogue is data, and the page is the same length whether
   there are twenty-one works or a hundred.

   Three things happen here and they are kept apart on purpose:
     buildFace()  — what a card looks like. One component, used by the fan, the
                    table and the grid alike; restyling a card should not need
                    anything outside it and sketchbook.css to change.
     the fan      — holds exactly five, and refills as cards leave it.
     the table    — cards that have been played: draggable, and flippable. */
(function () {
    'use strict';

    var MANIFEST = 'assets/sketchbook/works.json';
    var BACK = 'Cards/back.jpg';

    // The hand is five wide in the design and the refill keeps it there; it is
    // named rather than written into three places.
    var HAND = 5;

    // The mockup's heading reads "Upcoming Cards (12/100)": a hundred is the
    // set the sketchbook is being built towards, not a count of anything that
    // exists, so it is a constant here and the numerator is the manifest.
    var PLANNED = 100;

    // A drag under this many pixels was someone clicking a card that happened
    // to wobble, not moving it. Above it the click is swallowed so a card is
    // never dropped and flipped by the same gesture.
    var DRAG_SLOP = 4;

    // Degrees between one card in the hand and the next.
    var FAN_TILT = 6.5;
    // Room left either side of the hand. The outermost card is tilted two steps,
    // so its corner reaches past its upright box and this has to cover that as
    // well as look like a margin.
    var FAN_EDGE = 24;

    var felt = document.getElementById('felt');
    var surface = document.getElementById('surface');
    var fanEl = document.getElementById('fan');
    var playedEl = document.getElementById('played');
    var gridEl = document.getElementById('grid');
    var emptyEl = document.getElementById('grid-empty');
    var countEl = document.getElementById('upcoming-count');
    if (!felt || !surface || !fanEl || !playedEl || !gridEl) return;

    var works = [];      // every work, in manifest order — this is the grid
    var deck = [];       // what the fan draws from next
    var hand = [];       // the five card elements currently in the fan, in order
    var topZ = 1;        // last card touched sits above the rest
    var gridTiles = {};  // id -> the tile in the catalogue, so it can be marked
    var dealt = {};      // ids that have been played at least once
    var dealtCount = 0;

    /* ---------------- the card face ---------------- */

    // The whole of a card's appearance. `still` asks for the poster frame
    // instead of the animation: the seven GIFs run to 18 MB each, which is fine
    // for the five cards in a hand and not fine for a grid that paints every
    // work at once.
    function buildFace(work, still) {
        var face = document.createElement('div');
        face.className = 'card-face card-face--front';

        var img = document.createElement('img');
        var file = (still && work.poster) ? work.poster : work.file;
        img.src = 'assets/sketchbook/' + file;
        // The shimmer is on in the markup and skeleton.js takes it off when the
        // image decodes. It watches for images added at runtime, which is every
        // image on this page.
        img.setAttribute('data-skel', '');
        // The card's shape is fixed by CSS, so these do not reserve the box —
        // they are here so the intrinsic ratio is known for `object-fit` and so
        // the tag says what it is holding.
        img.width = work.width;
        img.height = work.height;
        img.alt = work.title;
        img.decoding = 'async';
        // An image is draggable by default, and pressing on one and moving
        // hands the gesture to the browser's own drag-and-drop: the pointer
        // events stop arriving and the card is left behind after about thirty
        // pixels. The card's drag is the only drag this page wants.
        img.draggable = false;
        face.appendChild(img);

        var name = document.createElement('div');
        name.className = 'card-name';
        var cat = document.createElement('span');
        cat.className = 'cat';
        cat.textContent = work.category;
        var title = document.createElement('span');
        title.className = 'name';
        // Verbatim from the live page. The casing there is uneven — "kusama"
        // beside "Mondrian" — but normalising it would mean editing someone's
        // titles, and "tech@nyu" is the case it would get wrong.
        title.textContent = work.title;
        name.appendChild(cat);
        name.appendChild(title);
        face.appendChild(name);
        return face;
    }

    // The deck's own back, which is what a card on the table turns over onto.
    function buildBackArt() {
        var img = document.createElement('img');
        img.src = BACK;
        img.setAttribute('data-skel', '');
        img.alt = '';
        img.decoding = 'async';
        img.draggable = false;
        return img;
    }

    // The information side, which is what the card in the modal turns over onto
    // instead. Everything on it comes from the manifest; a field the manifest
    // has nothing for is left out rather than printed empty.
    function buildDetail(work) {
        var d = document.createElement('div');
        d.className = 'card-detail';

        var cat = document.createElement('div');
        cat.className = 'detail-cat';
        cat.setAttribute('data-field', 'category');
        cat.textContent = work.category || 'Sketchbook';
        d.appendChild(cat);

        var h = document.createElement('h3');
        h.className = 'detail-title';
        h.setAttribute('data-field', 'title');
        h.textContent = work.title;
        d.appendChild(h);

        var rows = [
            ['format', 'Format', String(work.file || '').split('.').pop().toUpperCase()],
            ['size', 'Size', work.width && work.height ? work.width + ' \u00d7 ' + work.height : ''],
        ];
        var dl = document.createElement('dl');
        for (var i = 0; i < rows.length; i++) {
            if (!rows[i][2]) continue;
            var dt = document.createElement('dt');
            dt.textContent = rows[i][1];
            var dd = document.createElement('dd');
            dd.setAttribute('data-field', rows[i][0]);
            dd.textContent = rows[i][2];
            dl.appendChild(dt);
            dl.appendChild(dd);
        }
        d.appendChild(dl);

        var note = document.createElement('p');
        note.className = 'detail-note';
        note.textContent = work.animated
            ? 'Animated \u2014 the card plays it in place.'
            : 'One of the hundred cards this sketchbook is being built towards.';
        d.appendChild(note);
        return d;
    }

    // A card element. An interactive one is a wrapper holding two controls: the
    // card's own face, which turns over, and the expand control addExpand()
    // puts in its corner. They are two buttons and not one because a button
    // cannot contain a button, and because turning a card over and opening it
    // are different things that must not share a gesture. A grid tile is
    // neither - it is a <figure> holding the same face and no behaviour.
    function buildCard(work, opts) {
        opts = opts || {};
        var el = document.createElement(opts.interactive ? 'div' : 'figure');
        el.className = 'card';
        el.dataset.id = work.id;
        el.dataset.title = work.title;
        // Held on the element so the expand control and the modal can read the
        // work straight back rather than looking it up by id.
        el.__work = work;

        var inner = document.createElement('div');
        inner.className = 'card-inner';
        inner.appendChild(buildFace(work, opts.still));

        // Grid tiles never turn over, so they are not given a back to turn to.
        if (opts.interactive) {
            var back = document.createElement('div');
            back.className = 'card-face card-face--back';
            back.appendChild(opts.detail ? buildDetail(work) : buildBackArt());
            inner.appendChild(back);

            var flip = document.createElement('button');
            flip.className = 'card-flip';
            flip.type = 'button';
            flip.appendChild(inner);
            el.appendChild(flip);
            el.flipBtn = flip;
        } else {
            el.appendChild(inner);
        }
        return el;
    }

    // Turning a card over. The pressed state goes on the button rather than on
    // the wrapper, because the button is the control a screen reader is on.
    function toggleFlip(el) {
        el.classList.toggle('is-flipped');
        var on = el.classList.contains('is-flipped');
        if (el.flipBtn) el.flipBtn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }

    // Two corners pulling apart: the same idea the live sketchbook's card uses.
    var EXPAND_SVG = '<svg viewBox="0 0 15 15" fill="none" aria-hidden="true">'
        + '<path d="M9 1.5h4.5V6M6 13.5H1.5V9M13.5 1.5l-5 5M1.5 13.5l5-5" stroke="currentColor"'
        + ' stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';

    function addExpand(el) {
        var b = document.createElement('button');
        b.className = 'card-expand';
        b.type = 'button';
        b.setAttribute('aria-label', 'Expand ' + el.dataset.title);
        b.innerHTML = EXPAND_SVG;
        // The card underneath turns over on click and starts a drag on
        // pointerdown, and both of those listeners are on the wrapper this
        // button sits inside. Stopping here is what keeps the two gestures
        // apart without the wrapper having to know what is in its corner.
        b.addEventListener('pointerdown', function (e) { e.stopPropagation(); });
        b.addEventListener('click', function (e) {
            e.stopPropagation();
            openModal(el.__work, b);
        });
        el.appendChild(b);
        return b;
    }

    function place(el, x, y, rot) {
        el.style.setProperty('--x', x + 'px');
        el.style.setProperty('--y', y + 'px');
        el.style.setProperty('--rot', rot + 'deg');
    }
    var readVar = function (el, n) { return parseFloat(el.style.getPropertyValue(n)) || 0; };

    /* ---------------- the fan ---------------- */

    // How far apart the cards in the hand sit. Just over half a card, so they
    // overlap the way a hand does — but never wider than the table: five cards
    // at the desktop spread come to 392px, which is more than the canvas is
    // wide on a phone, and the outer two hang off the edge and get clipped.
    function fanSpread() {
        var loose = 0.54 * fanCardW();
        var room = felt.getBoundingClientRect().width - fanCardW() - 2 * FAN_EDGE;
        return Math.max(0, Math.min(loose, room / (HAND - 1)));
    }

    // Where card `i` of five sits inside #fan, which is itself exactly one card
    // wide — so the middle card is at zero and the others step out from it.
    function fanSlot(i) {
        var mid = (HAND - 1) / 2;
        var off = i - mid;
        return {
            x: off * fanSpread(),
            y: off * off * 5,                 // outer cards ride lower, arcing the hand
            rot: off * FAN_TILT,
        };
    }

    // A card in the hand. Read from the fan's real box rather than from the
    // custom property: the property is in whatever unit the media query left it
    // in, and the fan is sized off the same value, so one measurement keeps the
    // two in step.
    function fanCardW() { return fanEl.getBoundingClientRect().width; }
    function fanCardH() { return fanEl.getBoundingClientRect().height; }

    // A card on the table, which is smaller - at the hand's size only three or
    // four fit before they start burying each other. Taken from the custom
    // property and not measured off a card already down, because a played card
    // is tilted (its bounding box is wider and taller than the card itself) and
    // because the first card has to be placed before there is one to measure.
    function playedW() {
        var v = parseFloat(getComputedStyle(document.documentElement)
            .getPropertyValue('--card-w-played'));
        return v || fanCardW();
    }
    function playedH() { return playedW() * 7 / 5; }

    function layOutFan() {
        for (var i = 0; i < hand.length; i++) {
            var s = fanSlot(i);
            place(hand[i], s.x, s.y, s.rot);
            hand[i].style.zIndex = String(i + 1);
        }
    }

    // Draws one onto the end of the hand. The hand is a queue: playing a card
    // takes it out and everything behind it closes up, so a new card always
    // joins at the back rather than filling the hole the played one left.
    // `rise` is false for the five the page starts with, which are simply
    // there rather than arriving.
    function draw(rise) {
        if (!deck.length) refillDeck();
        var work = deck.shift();
        if (!work) return null;
        var el = buildCard(work, { interactive: true });
        el.setAttribute('data-cursor', 'play this card');
        el.flipBtn.setAttribute('aria-label', 'Play ' + work.title);
        // Held on the element so play() can take it off again: the card keeps
        // living once it reaches the table, where a click means something else.
        el.__play = function () { play(el); };
        el.addEventListener('click', el.__play);
        if (rise) el.classList.add('is-entering');
        fanEl.appendChild(el);
        hand.push(el);
        return el;
    }

    // The hand outlives the manifest: with twenty-one works and five in hand
    // the deck runs out after sixteen plays, and "always five" has to keep
    // being true after that. Anything already in the hand is held back so the
    // same work is never in it twice.
    function refillDeck() {
        var held = {};
        for (var i = 0; i < hand.length; i++) if (hand[i]) held[hand[i].dataset.id] = true;
        deck = shuffle(works.filter(function (w) { return !held[w.id]; }));
    }

    function shuffle(list) {
        var a = list.slice();
        for (var i = a.length - 1; i > 0; i--) {
            var j = Math.floor(Math.random() * (i + 1));
            var t = a[i]; a[i] = a[j]; a[j] = t;
        }
        return a;
    }

    /* ---------------- panning the table ---------------- */

    /* The surface is larger than the window onto it, so there is somewhere to
       push cards to. Dragging anywhere on the table that is not a card slides
       it; the hand is outside the surface and stays where it is. */

    var pan = { x: 0, y: 0 };

    function panLimits() {
        var f = felt.getBoundingClientRect();
        var s = surface.getBoundingClientRect();
        // Never positive: the surface's top left corner may sit at or left of
        // the window's, never right of it, or a strip of nothing shows.
        return { minX: Math.min(0, f.width - s.width), minY: Math.min(0, f.height - s.height) };
    }

    function applyPan() {
        var l = panLimits();
        pan.x = Math.min(0, Math.max(l.minX, pan.x));
        pan.y = Math.min(0, Math.max(l.minY, pan.y));
        surface.style.setProperty('--px', pan.x + 'px');
        surface.style.setProperty('--py', pan.y + 'px');
    }

    // Open in the middle of the table, so there is room to pan in every
    // direction rather than only down and to the right.
    function centrePan() {
        var l = panLimits();
        pan.x = l.minX / 2;
        pan.y = l.minY / 2;
        applyPan();
    }

    var panDrag = null;

    felt.addEventListener('pointerdown', function (e) {
        if (e.button !== undefined && e.button !== 0) return;
        // A press that lands on a card belongs to that card.
        if (e.target.closest && e.target.closest('.card')) return;
        panDrag = {
            id: e.pointerId,
            px: e.clientX, py: e.clientY,
            ox: pan.x, oy: pan.y,
            moved: false,
        };
        if (felt.setPointerCapture) felt.setPointerCapture(e.pointerId);
    });

    felt.addEventListener('pointermove', function (e) {
        if (!panDrag || e.pointerId !== panDrag.id) return;
        var dx = e.clientX - panDrag.px, dy = e.clientY - panDrag.py;
        if (!panDrag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
        if (!panDrag.moved) { panDrag.moved = true; felt.classList.add('is-panning'); }
        pan.x = panDrag.ox + dx;
        pan.y = panDrag.oy + dy;
        applyPan();
    });

    function endPan(e) {
        if (!panDrag || e.pointerId !== panDrag.id) return;
        if (felt.releasePointerCapture && felt.hasPointerCapture && felt.hasPointerCapture(e.pointerId)) {
            felt.releasePointerCapture(e.pointerId);
        }
        felt.classList.remove('is-panning');
        panDrag = null;
    }
    felt.addEventListener('pointerup', endPan);
    felt.addEventListener('pointercancel', endPan);

    /* ---------------- playing a card ---------------- */

    // How far a tilted card's corners reach past the box it would occupy
    // square-on. #felt clips what leaves it, so without this a card sitting at
    // x = 0 with a 10 degree tilt has its top corner sliced off.
    function overhang(rotDeg) {
        var a = Math.abs(rotDeg) * Math.PI / 180;
        var w = playedW(), h = playedH();
        var sin = Math.sin(a), cos = Math.cos(a);
        return {
            x: Math.ceil((w * cos + h * sin - w) / 2),
            y: Math.ceil((w * sin + h * cos - h) / 2),
        };
    }

    // The rectangle a card of this tilt may be placed in and stay whole, in the
    // surface's own coordinates. It is the whole surface and not the visible
    // part: a card dragged off the edge of the window is still on the table,
    // and panning back to it is the point of the table being bigger.
    function bounds(rotDeg) {
        var s = surface.getBoundingClientRect();
        var o = overhang(rotDeg);
        var pad = 8;
        return {
            minX: o.x + pad,
            maxX: Math.max(o.x + pad, s.width - playedW() - o.x - pad),
            minY: o.y + pad,
            maxY: Math.max(o.y + pad, s.height - playedH() - o.y - pad),
        };
    }

    // Somewhere on the table, biased towards the middle, and never over the
    // fan — a card that landed on the hand would be unreachable behind it.
    function landingSpot(rot) {
        var f = felt.getBoundingClientRect();
        var sr = surface.getBoundingClientRect();
        var w = playedW(), h = playedH();
        var b = bounds(rot);
        var o = overhang(rot);

        // A card is dealt into view. The surface is larger than the window onto
        // it, and being handed a card that landed somewhere you have to go
        // looking for would be a strange way to be handed one — so the landing
        // band is the visible part of the surface, in surface coordinates,
        // wherever the table happens to be panned to.
        var viewX = f.left - sr.left, viewY = f.top - sr.top;
        var fanTop = fanEl.getBoundingClientRect().top - sr.top;

        var minX = Math.max(b.minX, viewX + o.x + 8);
        var maxX = Math.min(b.maxX, viewX + f.width - w - o.x - 8);
        var minY = Math.max(b.minY, viewY + o.y + 8);
        var maxY = Math.min(b.maxY, fanTop - h - o.y - 20);
        // A short viewport can leave no band at all between the padding and the
        // hand. Landing on the fan is worse than landing tight to the top, so
        // the top wins and the card is simply high on the table.
        if (maxX < minX) maxX = minX;
        if (maxY < minY) maxY = minY;

        // The average of two uniform draws is triangular: still random, but it
        // clusters towards the centre, which is where the mockup's played card
        // sits.
        //
        // Candidates are scored rather than taken as soon as one is clear. A
        // card only covers another when it overlaps on both axes, so clearing
        // either one is far enough; the score is how far the nearest card
        // already down is on its better axis, in units of half a card, and the
        // best of the batch wins. Taking the first clear draw was fine for two
        // or three cards and fell apart at seven, where most draws touch
        // something and the twelfth was accepted whatever it looked like.
        var down = playedEl.children;
        var best = null, bestScore = -1;
        for (var t = 0; t < 60; t++) {
            var x = minX + (maxX - minX) * (Math.random() + Math.random()) / 2;
            var y = minY + (maxY - minY) * (Math.random() + Math.random()) / 2;
            var score = Infinity;
            for (var i = 0; i < down.length; i++) {
                var dx = Math.abs(readVar(down[i], '--x') - x);
                var dy = Math.abs(readVar(down[i], '--y') - y);
                var clear = Math.max(dx / (w * 0.5), dy / (h * 0.5));
                if (clear < score) score = clear;
            }
            if (score > bestScore) { bestScore = score; best = { x: x, y: y }; }
            // 1 is touching exactly; a little past it is clear with room to
            // spare for the rounding a measurement goes through.
            if (bestScore >= 1.06) break;
        }
        return best;
    }

    function play(el) {
        var i = hand.indexOf(el);
        if (i === -1) return;

        // Where it is now, in the same coordinates the landing spot is in, so
        // the flight is one transition between two real positions rather than
        // an animation the layout has to be talked out of.
        var sr = surface.getBoundingClientRect();
        var fan = fanEl.getBoundingClientRect();
        var slot = fanSlot(i);
        var fromX = (fan.left - sr.left) + slot.x;
        var fromY = (fan.top - sr.top) + slot.y;

        el.removeEventListener('click', el.__play);
        el.__play = null;
        // Out of the queue, not blanked in place: the cards behind it close up
        // and the replacement joins at the back.
        hand.splice(i, 1);
        playedEl.appendChild(el);

        el.className = 'card';
        el.style.zIndex = String(++topZ);
        el.setAttribute('data-cursor', 'flip · drag');
        el.flipBtn.setAttribute('aria-label', el.dataset.title + ' — click to turn over, drag to move');
        el.flipBtn.setAttribute('aria-pressed', 'false');
        // It leaves the hand at the hand's size and arrives at the table's, so
        // the width has to start explicitly at the old value or there is
        // nothing for the transition to run from and the shrink is a snap at
        // the moment the card is let go of.
        el.style.width = fanCardW() + 'px';
        place(el, fromX, fromY, slot.rot);

        // A slight tilt, and never quite square: a card dealt flat onto the
        // table reads as placed rather than thrown. Settled before the landing
        // spot because the tilt is what decides how far from the edges a whole
        // card can sit.
        // Three to nine degrees. Twelve was enough to swing the expand control
        // noticeably in from the corner it is meant to sit in, and on a card
        // this size the gentler tilt still reads as thrown rather than placed.
        var rot = (Math.random() < 0.5 ? -1 : 1) * (3 + Math.random() * 6);
        var to = landingSpot(rot);

        // Read back a layout value so the browser cannot fold the two writes
        // into one and skip the transition entirely.
        void el.offsetWidth;
        el.classList.add('is-dealing');
        el.style.width = '';
        place(el, to.x, to.y, rot);
        el.addEventListener('transitionend', function done(e) {
            if (e.propertyName !== 'transform') return;
            el.classList.remove('is-dealing');
            el.removeEventListener('transitionend', done);
        });

        makePlayable(el);
        addExpand(el);

        markDealt(el.__work);

        // The hand is five wide at all times, so the gap closes immediately.
        var added = draw(true);
        layOutFan();
        if (added) {
            // A frame with the card laid out but still offset, so removing the
            // class has somewhere to animate from. Without the reflow the two
            // writes fold into one and it simply appears.
            void added.offsetWidth;
            requestAnimationFrame(function () { added.classList.remove('is-entering'); });
        }
    }

    /* ---------------- a card on the table ---------------- */

    function makePlayable(el) {
        var drag = null;
        // Set when a gesture turned out to be a drag, so the click that follows
        // it does not also flip the card over.
        var swallowClick = false;

        el.addEventListener('pointerdown', function (e) {
            if (e.button !== undefined && e.button !== 0) return;
            el.style.zIndex = String(++topZ);
            drag = {
                id: e.pointerId,
                px: e.clientX, py: e.clientY,
                ox: readVar(el, '--x'), oy: readVar(el, '--y'),
                moved: false,
            };
            // Capture, so a fast drag that outruns the pointer keeps sending
            // moves here instead of to whatever is now underneath it.
            if (el.setPointerCapture) el.setPointerCapture(e.pointerId);
        });

        // Belt to the images' braces: a card is a <button> holding pictures,
        // and anything in it that the browser decides is draggable would take
        // the gesture away from the handlers below.
        el.addEventListener('dragstart', function (e) { e.preventDefault(); });

        el.addEventListener('pointermove', function (e) {
            if (!drag || e.pointerId !== drag.id) return;
            var dx = e.clientX - drag.px, dy = e.clientY - drag.py;
            if (!drag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
            if (!drag.moved) {
                drag.moved = true;
                // The flight, if it is still running, would fight the drag.
                el.classList.remove('is-dealing');
                el.classList.add('is-dragging');
            }
            // Bounds for this card's own tilt: #felt clips, and the corner of a
            // tilted card reaches further than its upright box does.
            var b = bounds(readVar(el, '--rot'));
            var x = Math.min(Math.max(drag.ox + dx, b.minX), b.maxX);
            var y = Math.min(Math.max(drag.oy + dy, b.minY), b.maxY);
            el.style.setProperty('--x', x + 'px');
            el.style.setProperty('--y', y + 'px');
        });

        function end(e) {
            if (!drag || e.pointerId !== drag.id) return;
            if (el.releasePointerCapture && el.hasPointerCapture && el.hasPointerCapture(e.pointerId)) {
                el.releasePointerCapture(e.pointerId);
            }
            el.classList.remove('is-dragging');
            swallowClick = drag.moved;
            drag = null;
        }
        el.addEventListener('pointerup', end);
        el.addEventListener('pointercancel', end);

        // Flipping is bound to click rather than to pointerup so that Enter and
        // Space on a focused card turn it over too.
        el.addEventListener('click', function () {
            if (swallowClick) { swallowClick = false; return; }
            toggleFlip(el);
        });
    }

    /* ---------------- the card, opened ---------------- */

    /* A card's expand control puts it in a modal, larger, over a blurred page.
       The card in there is built fresh on every open and thrown away on close:
       there is then never a second copy of a work sitting in the document, and
       the rise always has a new element to play on. */

    var modalEl = document.getElementById('card-modal');
    var modalPanel = modalEl && modalEl.querySelector('[role="dialog"]');
    var modalCardEl = document.getElementById('modal-card');
    var modalOpener = null;

    function modalFocusable() {
        var all = modalEl.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
        return Array.prototype.filter.call(all, function (el) {
            return !el.disabled && el.getClientRects().length > 0;
        });
    }

    function openModal(work, opener) {
        if (!modalEl || !modalCardEl || !work) return;
        modalOpener = opener || null;
        modalCardEl.innerHTML = '';

        var card = buildCard(work, { interactive: true, detail: true });
        card.setAttribute('data-cursor', 'turn it over');
        card.flipBtn.setAttribute('aria-label', work.title + ' — turn over to read about it');
        card.flipBtn.setAttribute('aria-pressed', 'false');
        card.addEventListener('click', function () { toggleFlip(card); });
        modalCardEl.appendChild(card);

        // The dialog is named after the work it is showing, so it announces
        // something better than "dialog" when it takes focus.
        if (modalPanel) modalPanel.setAttribute('aria-label', work.title);
        modalEl.removeAttribute('hidden');
        // On <body>, which propagates to the viewport, so the scrollbar goes
        // with it and the scrim measures exactly the window.
        document.body.classList.add('modal-open');

        var close = modalEl.querySelector('.modal-close');
        if (close) close.focus();
    }

    function closeModal() {
        if (!modalEl || modalEl.hasAttribute('hidden')) return;
        modalEl.setAttribute('hidden', '');
        document.body.classList.remove('modal-open');
        modalCardEl.innerHTML = '';
        // Back to the control that opened it, or focus is left on nothing and
        // the next Tab starts from the top of the page.
        if (modalOpener && document.contains(modalOpener)) modalOpener.focus();
        modalOpener = null;
    }

    if (modalEl) {
        // The scrim and the close button both carry data-modal-close, so the
        // two ways out are one listener rather than two that could drift.
        modalEl.addEventListener('click', function (e) {
            if (e.target.closest && e.target.closest('[data-modal-close]')) closeModal();
        });

        document.addEventListener('keydown', function (e) {
            if (modalEl.hasAttribute('hidden')) return;
            if (e.key === 'Escape') { closeModal(); return; }
            if (e.key !== 'Tab') return;
            // Tab must not walk out of the modal and start operating the page
            // that is blurred behind it. Only the two ends are handled; in
            // between, the browser's own order is the right one.
            var f = modalFocusable();
            if (!f.length) { e.preventDefault(); return; }
            var i = f.indexOf(document.activeElement);
            var next = e.shiftKey ? i - 1 : i + 1;
            if (i === -1 || next < 0 || next >= f.length) {
                e.preventDefault();
                f[e.shiftKey ? f.length - 1 : 0].focus();
            }
        });
    }

    /* ---------------- the catalogue ---------------- */

    function buildGrid() {
        var frag = document.createDocumentFragment();
        for (var i = 0; i < works.length; i++) {
            var tile = buildCard(works[i], { still: true });
            // In the document from the start and shown only once the work has
            // been dealt out, so the tile is marked without the grid reflowing.
            var flag = document.createElement('span');
            flag.className = 'played-flag';
            flag.textContent = 'Played';
            tile.appendChild(flag);
            gridTiles[works[i].id] = tile;
            frag.appendChild(tile);
        }
        gridEl.appendChild(frag);
        updateCount();
    }

    // What is still to come, not what exists: a card you have played is no
    // longer upcoming. The hundred is the set the sketchbook is being built
    // towards, so only the numerator moves.
    function updateCount() {
        if (!countEl) return;
        countEl.textContent = '(' + Math.max(0, works.length - dealtCount) + '/' + PLANNED + ')';
    }

    // Counted once per work, however many times it comes back round: the deck
    // reshuffles after sixteen plays, and a work dealt twice has not become two
    // fewer cards to come.
    function markDealt(work) {
        if (!work || dealt[work.id]) return;
        dealt[work.id] = true;
        dealtCount++;
        var tile = gridTiles[work.id];
        if (tile) tile.classList.add('is-played');
        updateCount();
    }

    /* ---------------- start ---------------- */

    fetch(MANIFEST)
        .then(function (r) {
            if (!r.ok) throw new Error('works.json: HTTP ' + r.status);
            return r.json();
        })
        .then(function (data) {
            works = (data && data.works) || [];
            if (!works.length) throw new Error('works.json held no works');
            buildGrid();
            deck = shuffle(works);
            for (var i = 0; i < HAND; i++) draw(false);
            layOutFan();
            centrePan();
        })
        .catch(function (err) {
            // The catalogue is the page; without it there is nothing to show,
            // and an empty grid with a heading counting to zero would read as a
            // sketchbook with nothing in it rather than as a page that failed.
            if (emptyEl) emptyEl.hidden = false;
            if (countEl) countEl.textContent = '';
            console.error('[sketchbook]', err);
        });

    // The fan is placed in pixels off its own measured width, so a resize that
    // crosses the breakpoint has to re-lay it out.
    var resizeTimer = null;
    window.addEventListener('resize', function () {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(function () {
            layOutFan();
            // The surface is sized in percentages, so its limits move with the
            // window and a pan that was legal a moment ago may not be.
            applyPan();
        }, 120);
    });
})();
