/* The sketchbook: a hand of cards you deal onto a table, and the catalogue.
   ---------------------------------------------------------------------------
   Classic script, no imports, no build step — the same shape as site.js and
   skeleton.js, because these pages are plain HTML that works from any static
   server and the day one of them needs a bundler to run is the day it stops
   being that.

   The works come from assets/sketchbook/works.json, which was generated by a
   one-pass scrape of the live Framer sketchbook (its provenance is recorded in
   the file itself). Reading it rather than writing a hundred <img> tags by hand
   is the point: the catalogue is data, and the page is the same length whether
   there are twenty-one works or a hundred.

   Three things happen here and they are kept apart on purpose:
     buildFace()  — what a card looks like. One component, used by the fan, the
                    table and the grid alike; restyling a card should not need
                    anything outside it and sketchbook.css to change.
     the fan      — holds exactly five, and refills as cards leave it.
     the table    — cards that have been played: draggable, and flippable. */
(function () {
    'use strict';

    var MANIFEST = 'assets/sketchbook/works.json';
    var BACK = 'Cards/back.jpg';

    // The hand is five wide in the design and the refill keeps it there; it is
    // named rather than written into three places.
    var HAND = 5;

    // The mockup's heading reads "Upcoming Cards (12/100)": a hundred is the
    // set the sketchbook is being built towards, not a count of anything that
    // exists, so it is a constant here and the numerator is the manifest.
    var PLANNED = 100;

    // A drag under this many pixels was someone clicking a card that happened
    // to wobble, not moving it. Above it the click is swallowed so a card is
    // never dropped and flipped by the same gesture.
    var DRAG_SLOP = 4;

    // Degrees between one card in the hand and the next.
    var FAN_TILT = 6.5;
    // Room left either side of the hand. The outermost card is tilted two steps,
    // so its corner reaches past its upright box and this has to cover that as
    // well as look like a margin.
    var FAN_EDGE = 24;

    var felt = document.getElementById('felt');
    var fanEl = document.getElementById('fan');
    var playedEl = document.getElementById('played');
    var gridEl = document.getElementById('grid');
    var emptyEl = document.getElementById('grid-empty');
    var countEl = document.getElementById('upcoming-count');
    if (!felt || !fanEl || !playedEl || !gridEl) return;

    var works = [];      // every work, in manifest order — this is the grid
    var deck = [];       // what the fan draws from next
    var hand = [];       // the five card elements currently in the fan
    var topZ = 1;        // last card touched sits above the rest

    /* ---------------- the card face ---------------- */

    // The whole of a card's appearance. `still` asks for the poster frame
    // instead of the animation: the seven GIFs run to 18 MB each, which is fine
    // for the five cards in a hand and not fine for a grid that paints every
    // work at once.
    function buildFace(work, still) {
        var face = document.createElement('div');
        face.className = 'card-face card-face--front';

        var img = document.createElement('img');
        var file = (still && work.poster) ? work.poster : work.file;
        img.src = 'assets/sketchbook/' + file;
        // The shimmer is on in the markup and skeleton.js takes it off when the
        // image decodes. It watches for images added at runtime, which is every
        // image on this page.
        img.setAttribute('data-skel', '');
        // The card's shape is fixed by CSS, so these do not reserve the box —
        // they are here so the intrinsic ratio is known for `object-fit` and so
        // the tag says what it is holding.
        img.width = work.width;
        img.height = work.height;
        img.alt = work.title;
        img.decoding = 'async';
        // An image is draggable by default, and pressing on one and moving
        // hands the gesture to the browser's own drag-and-drop: the pointer
        // events stop arriving and the card is left behind after about thirty
        // pixels. The card's drag is the only drag this page wants.
        img.draggable = false;
        face.appendChild(img);

        var name = document.createElement('div');
        name.className = 'card-name';
        var cat = document.createElement('span');
        cat.className = 'cat';
        cat.textContent = work.category;
        var title = document.createElement('span');
        title.className = 'name';
        // Verbatim from the live page. The casing there is uneven — "kusama"
        // beside "Mondrian" — but normalising it would mean editing someone's
        // titles, and "tech@nyu" is the case it would get wrong.
        title.textContent = work.title;
        name.appendChild(cat);
        name.appendChild(title);
        face.appendChild(name);
        return face;
    }

    // A card element: the face, plus the back it turns to. `interactive` is
    // false for grid tiles, which are the same face without a card's behaviour.
    function buildCard(work, opts) {
        opts = opts || {};
        var el = document.createElement(opts.interactive ? 'button' : 'figure');
        el.className = 'card';
        if (opts.interactive) el.type = 'button';
        el.dataset.id = work.id;
        el.dataset.title = work.title;

        var inner = document.createElement('div');
        inner.className = 'card-inner';
        inner.appendChild(buildFace(work, opts.still));

        // Grid tiles never turn over, so they are not given a back to turn to.
        if (opts.interactive) {
            var back = document.createElement('div');
            back.className = 'card-face card-face--back';
            var bimg = document.createElement('img');
            bimg.src = BACK;
            bimg.setAttribute('data-skel', '');
            bimg.alt = '';
            bimg.decoding = 'async';
            bimg.draggable = false;
            back.appendChild(bimg);
            inner.appendChild(back);
        }

        el.appendChild(inner);
        return el;
    }

    function place(el, x, y, rot) {
        el.style.setProperty('--x', x + 'px');
        el.style.setProperty('--y', y + 'px');
        el.style.setProperty('--rot', rot + 'deg');
    }
    var readVar = function (el, n) { return parseFloat(el.style.getPropertyValue(n)) || 0; };

    /* ---------------- the fan ---------------- */

    // How far apart the cards in the hand sit. Just over half a card, so they
    // overlap the way a hand does — but never wider than the table: five cards
    // at the desktop spread come to 392px, which is more than the canvas is
    // wide on a phone, and the outer two hang off the edge and get clipped.
    function fanSpread() {
        var loose = 0.54 * cardW();
        var room = felt.getBoundingClientRect().width - cardW() - 2 * FAN_EDGE;
        return Math.max(0, Math.min(loose, room / (HAND - 1)));
    }

    // Where card `i` of five sits inside #fan, which is itself exactly one card
    // wide — so the middle card is at zero and the others step out from it.
    function fanSlot(i) {
        var mid = (HAND - 1) / 2;
        var off = i - mid;
        return {
            x: off * fanSpread(),
            y: off * off * 5,                 // outer cards ride lower, arcing the hand
            rot: off * FAN_TILT,
        };
    }

    function cardW() {
        // Read from a real card rather than the custom property: the property is
        // in whatever unit the media query left it in, and the fan is sized off
        // the same value, so one measurement keeps them in step.
        return fanEl.getBoundingClientRect().width;
    }
    function cardH() {
        return fanEl.getBoundingClientRect().height;
    }

    function layOutFan() {
        for (var i = 0; i < hand.length; i++) {
            var s = fanSlot(i);
            place(hand[i], s.x, s.y, s.rot);
            hand[i].style.zIndex = String(i + 1);
        }
    }

    function drawInto(i) {
        if (!deck.length) refillDeck();
        var work = deck.shift();
        if (!work) return null;
        var el = buildCard(work, { interactive: true });
        el.setAttribute('data-cursor', 'play this card');
        el.setAttribute('aria-label', 'Play ' + work.title);
        // Held on the element so play() can take it off again: the card keeps
        // living once it reaches the table, where a click means something else.
        el.__play = function () { play(el); };
        el.addEventListener('click', el.__play);
        fanEl.appendChild(el);
        hand[i] = el;
        return el;
    }

    // The hand outlives the manifest: with twenty-one works and five in hand
    // the deck runs out after sixteen plays, and "always five" has to keep
    // being true after that. Anything already in the hand is held back so the
    // same work is never in it twice.
    function refillDeck() {
        var held = {};
        for (var i = 0; i < hand.length; i++) if (hand[i]) held[hand[i].dataset.id] = true;
        deck = shuffle(works.filter(function (w) { return !held[w.id]; }));
    }

    function shuffle(list) {
        var a = list.slice();
        for (var i = a.length - 1; i > 0; i--) {
            var j = Math.floor(Math.random() * (i + 1));
            var t = a[i]; a[i] = a[j]; a[j] = t;
        }
        return a;
    }

    /* ---------------- playing a card ---------------- */

    // How far a tilted card's corners reach past the box it would occupy
    // square-on. #felt clips what leaves it, so without this a card sitting at
    // x = 0 with a 10 degree tilt has its top corner sliced off.
    function overhang(rotDeg) {
        var a = Math.abs(rotDeg) * Math.PI / 180;
        var w = cardW(), h = cardH();
        var sin = Math.sin(a), cos = Math.cos(a);
        return {
            x: Math.ceil((w * cos + h * sin - w) / 2),
            y: Math.ceil((w * sin + h * cos - h) / 2),
        };
    }

    // The rectangle a card of this tilt may be placed in and stay whole.
    function bounds(rotDeg) {
        var f = felt.getBoundingClientRect();
        var o = overhang(rotDeg);
        var pad = 8;
        return {
            minX: o.x + pad,
            maxX: Math.max(o.x + pad, f.width - cardW() - o.x - pad),
            minY: o.y + pad,
            maxY: Math.max(o.y + pad, f.height - cardH() - o.y - pad),
            top: f.top, left: f.left,
        };
    }

    // Somewhere on the table, biased towards the middle, and never over the
    // fan — a card that landed on the hand would be unreachable behind it.
    function landingSpot(rot) {
        var f = felt.getBoundingClientRect();
        var w = cardW(), h = cardH();
        var b = bounds(rot);
        // The fan's own top edge in felt coordinates: the floor for a landing.
        var fanTop = fanEl.getBoundingClientRect().top - f.top;

        var minX = b.minX, maxX = b.maxX;
        var minY = b.minY, maxY = Math.min(b.maxY, fanTop - h - overhang(rot).y - 20);
        // A short viewport can leave no band at all between the padding and the
        // hand. Landing on the fan is worse than landing tight to the top, so
        // the top wins and the card is simply high on the table.
        if (maxY < minY) maxY = minY;

        // The average of two uniform draws is triangular: still random, but it
        // clusters towards the centre, which is where the mockup's played card
        // sits. Twelve tries at not covering a card already down; the last one
        // is taken regardless, so a crowded table still deals.
        var best = null;
        for (var t = 0; t < 12; t++) {
            var x = minX + (maxX - minX) * (Math.random() + Math.random()) / 2;
            var y = minY + (maxY - minY) * (Math.random() + Math.random()) / 2;
            var clear = true;
            var down = playedEl.children;
            for (var i = 0; i < down.length; i++) {
                var dx = readVar(down[i], '--x') - x, dy = readVar(down[i], '--y') - y;
                if (Math.abs(dx) < w * 0.5 && Math.abs(dy) < h * 0.5) { clear = false; break; }
            }
            best = { x: x, y: y };
            if (clear) break;
        }
        return best;
    }

    function play(el) {
        var i = hand.indexOf(el);
        if (i === -1) return;

        // Where it is now, in the same coordinates the landing spot is in, so
        // the flight is one transition between two real positions rather than
        // an animation the layout has to be talked out of.
        var f = felt.getBoundingClientRect();
        var fan = fanEl.getBoundingClientRect();
        var slot = fanSlot(i);
        var fromX = (fan.left - f.left) + slot.x;
        var fromY = (fan.top - f.top) + slot.y;

        el.removeEventListener('click', el.__play);
        el.__play = null;
        hand[i] = null;
        playedEl.appendChild(el);

        el.className = 'card';
        el.style.zIndex = String(++topZ);
        el.setAttribute('data-cursor', 'flip · drag');
        el.setAttribute('aria-label', el.dataset.title + ' — click to turn over, drag to move');
        place(el, fromX, fromY, slot.rot);

        // A slight tilt, and never quite square: a card dealt flat onto the
        // table reads as placed rather than thrown. Settled before the landing
        // spot because the tilt is what decides how far from the edges a whole
        // card can sit.
        var rot = (Math.random() < 0.5 ? -1 : 1) * (3 + Math.random() * 9);
        var to = landingSpot(rot);

        // Read back a layout value so the browser cannot fold the two writes
        // into one and skip the transition entirely.
        void el.offsetWidth;
        el.classList.add('is-dealing');
        place(el, to.x, to.y, rot);
        el.addEventListener('transitionend', function done(e) {
            if (e.propertyName !== 'transform') return;
            el.classList.remove('is-dealing');
            el.removeEventListener('transitionend', done);
        });

        makePlayable(el);

        // The hand is five wide at all times, so the gap closes immediately.
        drawInto(i);
        layOutFan();
    }

    /* ---------------- a card on the table ---------------- */

    function makePlayable(el) {
        var drag = null;
        // Set when a gesture turned out to be a drag, so the click that follows
        // it does not also flip the card over.
        var swallowClick = false;

        el.addEventListener('pointerdown', function (e) {
            if (e.button !== undefined && e.button !== 0) return;
            el.style.zIndex = String(++topZ);
            drag = {
                id: e.pointerId,
                px: e.clientX, py: e.clientY,
                ox: readVar(el, '--x'), oy: readVar(el, '--y'),
                moved: false,
            };
            // Capture, so a fast drag that outruns the pointer keeps sending
            // moves here instead of to whatever is now underneath it.
            if (el.setPointerCapture) el.setPointerCapture(e.pointerId);
        });

        // Belt to the images' braces: a card is a <button> holding pictures,
        // and anything in it that the browser decides is draggable would take
        // the gesture away from the handlers below.
        el.addEventListener('dragstart', function (e) { e.preventDefault(); });

        el.addEventListener('pointermove', function (e) {
            if (!drag || e.pointerId !== drag.id) return;
            var dx = e.clientX - drag.px, dy = e.clientY - drag.py;
            if (!drag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
            if (!drag.moved) {
                drag.moved = true;
                // The flight, if it is still running, would fight the drag.
                el.classList.remove('is-dealing');
                el.classList.add('is-dragging');
            }
            // Bounds for this card's own tilt: #felt clips, and the corner of a
            // tilted card reaches further than its upright box does.
            var b = bounds(readVar(el, '--rot'));
            var x = Math.min(Math.max(drag.ox + dx, b.minX), b.maxX);
            var y = Math.min(Math.max(drag.oy + dy, b.minY), b.maxY);
            el.style.setProperty('--x', x + 'px');
            el.style.setProperty('--y', y + 'px');
        });

        function end(e) {
            if (!drag || e.pointerId !== drag.id) return;
            if (el.releasePointerCapture && el.hasPointerCapture && el.hasPointerCapture(e.pointerId)) {
                el.releasePointerCapture(e.pointerId);
            }
            el.classList.remove('is-dragging');
            swallowClick = drag.moved;
            drag = null;
        }
        el.addEventListener('pointerup', end);
        el.addEventListener('pointercancel', end);

        // Flipping is bound to click rather than to pointerup so that Enter and
        // Space on a focused card turn it over too.
        el.addEventListener('click', function () {
            if (swallowClick) { swallowClick = false; return; }
            el.classList.toggle('is-flipped');
            el.setAttribute('aria-pressed', el.classList.contains('is-flipped') ? 'true' : 'false');
        });
    }

    /* ---------------- the catalogue ---------------- */

    function buildGrid() {
        var frag = document.createDocumentFragment();
        for (var i = 0; i < works.length; i++) {
            frag.appendChild(buildCard(works[i], { still: true }));
        }
        gridEl.appendChild(frag);
        if (countEl) countEl.textContent = '(' + works.length + '/' + PLANNED + ')';
    }

    /* ---------------- start ---------------- */

    fetch(MANIFEST)
        .then(function (r) {
            if (!r.ok) throw new Error('works.json: HTTP ' + r.status);
            return r.json();
        })
        .then(function (data) {
            works = (data && data.works) || [];
            if (!works.length) throw new Error('works.json held no works');
            buildGrid();
            deck = shuffle(works);
            for (var i = 0; i < HAND; i++) drawInto(i);
            layOutFan();
        })
        .catch(function (err) {
            // The catalogue is the page; without it there is nothing to show,
            // and an empty grid with a heading counting to zero would read as a
            // sketchbook with nothing in it rather than as a page that failed.
            if (emptyEl) emptyEl.hidden = false;
            if (countEl) countEl.textContent = '';
            console.error('[sketchbook]', err);
        });

    // The fan is placed in pixels off its own measured width, so a resize that
    // crosses the breakpoint has to re-lay it out.
    var resizeTimer = null;
    window.addEventListener('resize', function () {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(layOutFan, 120);
    });
})();
