/* The sketchbook: a hand of cards you deal onto a table, and the catalogue.
   ---------------------------------------------------------------------------
   Classic script, no imports, no build step — the same shape as site.js and
   skeleton.js, because these pages are plain HTML that works from any static
   server and the day one of them needs a bundler to run is the day it stops
   being that.

   The works come from assets/sketchbook/works.json, which was generated by a
   one-pass scrape of the live Framer sketchbook (its provenance is recorded in
   the file itself). Reading it rather than writing a hundred <img> tags by hand
   is the point: the catalogue is data, and the page is the same length whether
   there are twenty-one works or a hundred.

   Three things happen here and they are kept apart on purpose:
     buildFace()  — what a card looks like. One component, used by the fan, the
                    table and the grid alike; restyling a card should not need
                    anything outside it and sketchbook.css to change.
     the fan      — holds exactly five, and refills as cards leave it.
     the table    — cards that have been played: draggable, and flippable. */
(function () {
    'use strict';

    var MANIFEST = 'assets/sketchbook/works.json';
    var SVG_NS = 'http://www.w3.org/2000/svg';

    // The hand is five wide in the design and the refill keeps it there; it is
    // named rather than written into three places.
    var HAND = 5;

    // How long the pack takes to come together, riffle and go back out.
    var GATHER_MS = 560;
    var RIFFLE_MS = 240;
    var DEAL_STEP_MS = 42;      // between one card landing in the rack and the next

    // A drag under this many pixels was someone clicking a card that happened
    // to wobble, not moving it. Above it the click is swallowed so a card is
    // never dropped and flipped by the same gesture.
    var DRAG_SLOP = 4;

    // Degrees between one card in the hand and the next.
    var FAN_TILT = 6.5;
    // Room left either side of the hand. The outermost card is tilted two steps,
    // so its corner reaches past its upright box and this has to cover that as
    // well as look like a margin.
    var FAN_EDGE = 24;

    var felt = document.getElementById('felt');
    var surface = document.getElementById('surface');
    var fanEl = document.getElementById('fan');
    var playedEl = document.getElementById('played');
    var gridEl = document.getElementById('grid');
    var emptyEl = document.getElementById('grid-empty');
    var countEl = document.getElementById('upcoming-count');
    if (!felt || !surface || !fanEl || !playedEl || !gridEl) return;

    var works = [];      // every work the sketchbook has
    var hand = [];       // the card elements in the fan, in order
    var topZ = 1;        // last card touched sits above the rest
    var slotEls = [];    // the rack: one slot per work, made once and kept
    var rack = [];       // the works still to come, in the order they sit in it
    var tileOf = {};     // id -> the card currently in the rack
    var resetting = false;

    /* A work is in exactly one place at a time: in your hand, in the rack, or
       played onto the table. There is no separate deck behind the rack - the
       rack IS the deck, and the hand draws off the front of it, which is what
       makes the running order you can drag it into mean something. The count
       is simply the two you can still do something with: hand plus rack. */

    /* ---------------- the card face ---------------- */

    // The whole of a card's appearance. `still` asks for the poster frame
    // instead of the animation: the seven GIFs run to 18 MB each, which is fine
    // for the five cards in a hand and not fine for a grid that paints every
    // work at once.
    function buildFace(work, still) {
        var face = document.createElement('div');
        face.className = 'card-face card-face--front';

        var img = document.createElement('img');
        var file = (still && work.poster) ? work.poster : work.file;
        img.src = 'assets/sketchbook/' + file;
        // The shimmer is on in the markup and skeleton.js takes it off when the
        // image decodes. It watches for images added at runtime, which is every
        // image on this page.
        img.setAttribute('data-skel', '');
        // The card's shape is fixed by CSS, so these do not reserve the box —
        // they are here so the intrinsic ratio is known for `object-fit` and so
        // the tag says what it is holding.
        img.width = work.width;
        img.height = work.height;
        img.alt = work.title;
        img.decoding = 'async';
        // An image is draggable by default, and pressing on one and moving
        // hands the gesture to the browser's own drag-and-drop: the pointer
        // events stop arriving and the card is left behind after about thirty
        // pixels. The card's drag is the only drag this page wants.
        img.draggable = false;
        face.appendChild(img);

        var name = document.createElement('div');
        name.className = 'card-name';
        var cat = document.createElement('span');
        cat.className = 'cat';
        cat.textContent = work.category;
        var title = document.createElement('span');
        title.className = 'name';
        // Verbatim from the live page. The casing there is uneven — "kusama"
        // beside "Mondrian" — but normalising it would mean editing someone's
        // titles, and "tech@nyu" is the case it would get wrong.
        title.textContent = work.title;
        name.appendChild(cat);
        name.appendChild(title);
        face.appendChild(name);
        return face;
    }

    // The deck's own back, which is what a card on the table turns over onto.
    // Drawn rather than loaded: Cards/back.jpg was one fixed yellow whatever the
    // page was set to, and this is the same frame and mark built out of the
    // theme's tokens, so the blue back and the yellow-on-grey one are one piece
    // of markup instead of two exports to keep in step. Same geometry as the
    // footer's hand - a 25-wide border inset 35.5 in a 1059x1449 frame.
    function buildBackArt() {
        var out = document.createDocumentFragment();

        var svg = document.createElementNS(SVG_NS, 'svg');
        svg.setAttribute('class', 'card-back-frame');
        svg.setAttribute('viewBox', '0 0 1059 1449');
        // Stretched to the card rather than fitted: a percentage inset draws
        // unequal margins on a card that is taller than it is wide, and this
        // frame is meant to sit the same distance from all four edges.
        svg.setAttribute('preserveAspectRatio', 'none');
        svg.setAttribute('aria-hidden', 'true');
        svg.setAttribute('focusable', 'false');
        var r = document.createElementNS(SVG_NS, 'rect');
        r.setAttribute('x', '35.5');
        r.setAttribute('y', '35.5');
        r.setAttribute('width', String(1059 - 35.5 * 2));
        r.setAttribute('height', String(1449 - 35.5 * 2));
        r.setAttribute('rx', '24');
        r.setAttribute('fill', 'none');
        r.setAttribute('stroke', 'currentColor');
        r.setAttribute('stroke-width', '25');
        svg.appendChild(r);
        out.appendChild(svg);

        var mark = document.createElement('span');
        mark.className = 'card-back-mark';
        out.appendChild(mark);
        return out;
    }

    // The information side, which is what the card in the modal turns over onto
    // instead. Everything on it comes from the manifest; a field the manifest
    // has nothing for is left out rather than printed empty.
    function buildDetail(work) {
        var d = document.createElement('div');
        d.className = 'card-detail';

        var cat = document.createElement('div');
        cat.className = 'detail-cat';
        cat.setAttribute('data-field', 'category');
        cat.textContent = work.category || 'Sketchbook';
        d.appendChild(cat);

        var h = document.createElement('h3');
        h.className = 'detail-title';
        h.setAttribute('data-field', 'title');
        h.textContent = work.title;
        d.appendChild(h);

        var rows = [
            ['format', 'Format', String(work.file || '').split('.').pop().toUpperCase()],
            ['size', 'Size', work.width && work.height ? work.width + ' \u00d7 ' + work.height : ''],
        ];
        var dl = document.createElement('dl');
        for (var i = 0; i < rows.length; i++) {
            if (!rows[i][2]) continue;
            var dt = document.createElement('dt');
            dt.textContent = rows[i][1];
            var dd = document.createElement('dd');
            dd.setAttribute('data-field', rows[i][0]);
            dd.textContent = rows[i][2];
            dl.appendChild(dt);
            dl.appendChild(dd);
        }
        d.appendChild(dl);

        var note = document.createElement('p');
        note.className = 'detail-note';
        note.textContent = work.animated
            ? 'Animated \u2014 the card plays it in place.'
            : 'One of the hundred cards this sketchbook is being built towards.';
        d.appendChild(note);
        return d;
    }

    // A card element. An interactive one is a wrapper holding two controls: the
    // card's own face, which turns over, and the expand control addExpand()
    // puts in its corner. They are two buttons and not one because a button
    // cannot contain a button, and because turning a card over and opening it
    // are different things that must not share a gesture. A grid tile is
    // neither - it is a <figure> holding the same face and no behaviour.
    // Nothing here carries data-cursor. The rest of the site labels a link
    // with a pill because there is one thing that link does; a card is
    // something you handle, and a caption that changed every time the pointer
    // crossed a card was a running commentary on a table you are meant to be
    // playing on. The plain dot is enough, and on the mat even that gives way
    // to the grab hand.
    function buildCard(work, opts) {
        opts = opts || {};
        var el = document.createElement(opts.interactive ? 'div' : 'figure');
        el.className = 'card';
        el.dataset.id = work.id;
        el.dataset.title = work.title;
        // Held on the element so the expand control and the modal can read the
        // work straight back rather than looking it up by id.
        el.__work = work;

        var inner = document.createElement('div');
        inner.className = 'card-inner';
        inner.appendChild(buildFace(work, opts.still));

        // A rack tile is dealt in face down at the end of a round, so it needs a
        // back as much as a card on the table does; only its behaviour differs.
        if (opts.interactive || opts.back) {
            var back = document.createElement('div');
            back.className = 'card-face card-face--back';
            back.appendChild(opts.detail ? buildDetail(work) : buildBackArt());
            inner.appendChild(back);
        }

        if (opts.interactive) {
            var flip = document.createElement('button');
            flip.className = 'card-flip';
            flip.type = 'button';
            flip.appendChild(inner);
            el.appendChild(flip);
            el.flipBtn = flip;
        } else {
            el.appendChild(inner);
        }
        return el;
    }

    // Turning a card over. The pressed state goes on the button rather than on
    // the wrapper, because the button is the control a screen reader is on.
    function toggleFlip(el) {
        el.classList.toggle('is-flipped');
        var on = el.classList.contains('is-flipped');
        if (el.flipBtn) el.flipBtn.setAttribute('aria-pressed', on ? 'true' : 'false');
    }

    // Two corners pulling apart: the same idea the live sketchbook's card uses.
    var EXPAND_SVG = '<svg viewBox="0 0 15 15" fill="none" aria-hidden="true">'
        + '<path d="M9 1.5h4.5V6M6 13.5H1.5V9M13.5 1.5l-5 5M1.5 13.5l5-5" stroke="currentColor"'
        + ' stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';

    function addExpand(el) {
        var b = document.createElement('button');
        b.className = 'card-expand';
        b.type = 'button';
        b.setAttribute('aria-label', 'Expand ' + el.dataset.title);
        b.innerHTML = EXPAND_SVG;
        // The card underneath turns over on click and starts a drag on
        // pointerdown, and both of those listeners are on the wrapper this
        // button sits inside. Stopping here is what keeps the two gestures
        // apart without the wrapper having to know what is in its corner.
        b.addEventListener('pointerdown', function (e) { e.stopPropagation(); });
        b.addEventListener('click', function (e) {
            e.stopPropagation();
            openModal(el.__work, b);
        });

        el.appendChild(b);
        return b;
    }

    function place(el, x, y, rot) {
        el.style.setProperty('--x', x + 'px');
        el.style.setProperty('--y', y + 'px');
        el.style.setProperty('--rot', rot + 'deg');
    }
    var readVar = function (el, n) { return parseFloat(el.style.getPropertyValue(n)) || 0; };

    /* ---------------- the fan ---------------- */

    // How far apart the cards in the hand sit. Just over half a card, so they
    // overlap the way a hand does — but never wider than the table: five cards
    // at the desktop spread come to 392px, which is more than the canvas is
    // wide on a phone, and the outer two hang off the edge and get clipped.
    function fanSpread(n) {
        // The hand is five until the rack runs dry, and then it empties one
        // card at a time; the spread has to be worked out from what is actually
        // being held or the last two cards sit a whole hand apart.
        var count = Math.max(2, n || hand.length || HAND);
        var loose = 0.54 * fanCardW();
        var room = felt.getBoundingClientRect().width - fanCardW() - 2 * FAN_EDGE;
        return Math.max(0, Math.min(loose, room / (count - 1)));
    }

    // Where card `i` of five sits inside #fan, which is itself exactly one card
    // wide — so the middle card is at zero and the others step out from it.
    function fanSlot(i, n) {
        var count = n || hand.length || HAND;
        var mid = (count - 1) / 2;
        var off = i - mid;
        return {
            x: off * fanSpread(count),
            y: off * off * 5,                 // outer cards ride lower, arcing the hand
            rot: off * FAN_TILT,
        };
    }

    // A card in the hand. Read from the fan's real box rather than from the
    // custom property: the property is in whatever unit the media query left it
    // in, and the fan is sized off the same value, so one measurement keeps the
    // two in step.
    function fanCardW() { return fanEl.getBoundingClientRect().width; }
    function fanCardH() { return fanEl.getBoundingClientRect().height; }

    // A card on the table, which is smaller - at the hand's size only three or
    // four fit before they start burying each other. Taken from the custom
    // property and not measured off a card already down, because a played card
    // is tilted (its bounding box is wider and taller than the card itself) and
    // because the first card has to be placed before there is one to measure.
    function playedW() {
        var v = parseFloat(getComputedStyle(document.documentElement)
            .getPropertyValue('--card-w-played'));
        return v || fanCardW();
    }
    function playedH() { return playedW() * 7 / 5; }

    function layOutFan() {
        for (var i = 0; i < hand.length; i++) {
            var s = fanSlot(i, hand.length);
            place(hand[i], s.x, s.y, s.rot);
            hand[i].style.zIndex = String(i + 1);
        }
    }

    // Draws the front of the rack onto the end of the hand. The hand is a
    // queue: playing a card takes it out and everything behind it closes up, so
    // a new card always joins at the back rather than filling the hole the
    // played one left. Returns null once the rack is empty - the hand then
    // simply gets shorter, because there is nothing left to refill it from.
    function draw(rise) {
        var work = takeFromRack(0);
        return work ? addToHand(work, rise) : null;
    }

    // `rise` is false for the cards a round opens with, which are simply there
    // rather than arriving.
    function addToHand(work, rise) {
        var el = buildCard(work, { interactive: true });
        el.flipBtn.setAttribute('aria-label', 'Play ' + work.title);
        // Held on the element so play() can take it off again: the card keeps
        // living once it reaches the table, where a click means something else.
        el.__play = function () { play(el); };
        el.addEventListener('click', el.__play);
        if (rise) el.classList.add('is-entering');
        fanEl.appendChild(el);
        hand.push(el);
        return el;
    }

    function shuffle(list) {
        var a = list.slice();
        for (var i = a.length - 1; i > 0; i--) {
            var j = Math.floor(Math.random() * (i + 1));
            var t = a[i]; a[i] = a[j]; a[j] = t;
        }
        return a;
    }

    /* ---------------- panning the table ---------------- */

    /* The surface is larger than the window onto it, so there is somewhere to
       push cards to. Dragging anywhere on the table that is not a card slides
       it; the hand is outside the surface and stays where it is. */

    var pan = { x: 0, y: 0 };

    function panLimits() {
        var f = felt.getBoundingClientRect();
        var s = surface.getBoundingClientRect();
        // Never positive: the surface's top left corner may sit at or left of
        // the window's, never right of it, or a strip of nothing shows.
        return { minX: Math.min(0, f.width - s.width), minY: Math.min(0, f.height - s.height) };
    }

    function applyPan() {
        var l = panLimits();
        pan.x = Math.min(0, Math.max(l.minX, pan.x));
        pan.y = Math.min(0, Math.max(l.minY, pan.y));
        surface.style.setProperty('--px', pan.x + 'px');
        surface.style.setProperty('--py', pan.y + 'px');
    }

    // Open in the middle of the table, so there is room to pan in every
    // direction rather than only down and to the right.
    function centrePan() {
        var l = panLimits();
        pan.x = l.minX / 2;
        pan.y = l.minY / 2;
        applyPan();
    }

    var panDrag = null;

    felt.addEventListener('pointerdown', function (e) {
        if (e.button !== undefined && e.button !== 0) return;
        // A press that lands on a card belongs to that card.
        if (e.target.closest && e.target.closest('.card')) return;
        panDrag = {
            id: e.pointerId,
            px: e.clientX, py: e.clientY,
            ox: pan.x, oy: pan.y,
            moved: false,
        };
        if (felt.setPointerCapture) felt.setPointerCapture(e.pointerId);
    });

    felt.addEventListener('pointermove', function (e) {
        if (!panDrag || e.pointerId !== panDrag.id) return;
        var dx = e.clientX - panDrag.px, dy = e.clientY - panDrag.py;
        if (!panDrag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
        if (!panDrag.moved) { panDrag.moved = true; felt.classList.add('is-panning'); }
        pan.x = panDrag.ox + dx;
        pan.y = panDrag.oy + dy;
        applyPan();
    });

    function endPan(e) {
        if (!panDrag || e.pointerId !== panDrag.id) return;
        if (felt.releasePointerCapture && felt.hasPointerCapture && felt.hasPointerCapture(e.pointerId)) {
            felt.releasePointerCapture(e.pointerId);
        }
        felt.classList.remove('is-panning');
        panDrag = null;
    }
    felt.addEventListener('pointerup', endPan);
    felt.addEventListener('pointercancel', endPan);

    /* ---------------- playing a card ---------------- */

    // How far a tilted card's corners reach past the box it would occupy
    // square-on. #felt clips what leaves it, so without this a card sitting at
    // x = 0 with a 10 degree tilt has its top corner sliced off.
    function overhang(rotDeg) {
        var a = Math.abs(rotDeg) * Math.PI / 180;
        var w = playedW(), h = playedH();
        var sin = Math.sin(a), cos = Math.cos(a);
        return {
            x: Math.ceil((w * cos + h * sin - w) / 2),
            y: Math.ceil((w * sin + h * cos - h) / 2),
        };
    }

    // The rectangle a card of this tilt may be placed in and stay whole, in the
    // surface's own coordinates. It is the whole surface and not the visible
    // part: a card dragged off the edge of the window is still on the table,
    // and panning back to it is the point of the table being bigger.
    function bounds(rotDeg) {
        var s = surface.getBoundingClientRect();
        var o = overhang(rotDeg);
        var pad = 8;
        return {
            minX: o.x + pad,
            maxX: Math.max(o.x + pad, s.width - playedW() - o.x - pad),
            minY: o.y + pad,
            maxY: Math.max(o.y + pad, s.height - playedH() - o.y - pad),
        };
    }

    // Somewhere on the table, biased towards the middle, and never over the
    // fan — a card that landed on the hand would be unreachable behind it.
    function landingSpot(rot) {
        var f = felt.getBoundingClientRect();
        var sr = surface.getBoundingClientRect();
        var w = playedW(), h = playedH();
        var b = bounds(rot);
        var o = overhang(rot);

        // A card is dealt into view. The surface is larger than the window onto
        // it, and being handed a card that landed somewhere you have to go
        // looking for would be a strange way to be handed one — so the landing
        // band is the visible part of the surface, in surface coordinates,
        // wherever the table happens to be panned to.
        var viewX = f.left - sr.left, viewY = f.top - sr.top;
        var fanTop = fanEl.getBoundingClientRect().top - sr.top;

        var minX = Math.max(b.minX, viewX + o.x + 8);
        var maxX = Math.min(b.maxX, viewX + f.width - w - o.x - 8);
        var minY = Math.max(b.minY, viewY + o.y + 8);
        var maxY = Math.min(b.maxY, fanTop - h - o.y - 20);
        // A short viewport can leave no band at all between the padding and the
        // hand. Landing on the fan is worse than landing tight to the top, so
        // the top wins and the card is simply high on the table.
        if (maxX < minX) maxX = minX;
        if (maxY < minY) maxY = minY;

        // The average of two uniform draws is triangular: still random, but it
        // clusters towards the centre, which is where the mockup's played card
        // sits.
        //
        // Candidates are scored rather than taken as soon as one is clear. A
        // card only covers another when it overlaps on both axes, so clearing
        // either one is far enough; the score is how far the nearest card
        // already down is on its better axis, in units of half a card, and the
        // best of the batch wins. Taking the first clear draw was fine for two
        // or three cards and fell apart at seven, where most draws touch
        // something and the twelfth was accepted whatever it looked like.
        var down = playedEl.children;
        var best = null, bestScore = -1;
        for (var t = 0; t < 60; t++) {
            var x = minX + (maxX - minX) * (Math.random() + Math.random()) / 2;
            var y = minY + (maxY - minY) * (Math.random() + Math.random()) / 2;
            var score = Infinity;
            for (var i = 0; i < down.length; i++) {
                var dx = Math.abs(readVar(down[i], '--x') - x);
                var dy = Math.abs(readVar(down[i], '--y') - y);
                var clear = Math.max(dx / (w * 0.5), dy / (h * 0.5));
                if (clear < score) score = clear;
            }
            if (score > bestScore) { bestScore = score; best = { x: x, y: y }; }
            // 1 is touching exactly; a little past it is clear with room to
            // spare for the rounding a measurement goes through.
            if (bestScore >= 1.06) break;
        }
        return best;
    }

    function play(el) {
        if (resetting) return;
        var i = hand.indexOf(el);
        if (i === -1) return;

        // Where it is now, in the same coordinates the landing spot is in, so
        // the flight is one transition between two real positions rather than
        // an animation the layout has to be talked out of.
        var sr = surface.getBoundingClientRect();
        var fan = fanEl.getBoundingClientRect();
        var slot = fanSlot(i);
        var fromX = (fan.left - sr.left) + slot.x;
        var fromY = (fan.top - sr.top) + slot.y;

        el.removeEventListener('click', el.__play);
        el.__play = null;
        // Out of the queue, not blanked in place: the cards behind it close up
        // and the replacement joins at the back.
        hand.splice(i, 1);
        playedEl.appendChild(el);

        el.className = 'card';
        el.style.zIndex = String(++topZ);
        el.flipBtn.setAttribute('aria-label', el.dataset.title + ' — click to turn over, drag to move');
        el.flipBtn.setAttribute('aria-pressed', 'false');
        // It leaves the hand at the hand's size and arrives at the table's, so
        // the width has to start explicitly at the old value or there is
        // nothing for the transition to run from and the shrink is a snap at
        // the moment the card is let go of.
        el.style.width = fanCardW() + 'px';
        place(el, fromX, fromY, slot.rot);

        // A slight tilt, and never quite square: a card dealt flat onto the
        // table reads as placed rather than thrown. Settled before the landing
        // spot because the tilt is what decides how far from the edges a whole
        // card can sit.
        // Three to nine degrees. Twelve was enough to swing the expand control
        // noticeably in from the corner it is meant to sit in, and on a card
        // this size the gentler tilt still reads as thrown rather than placed.
        var rot = (Math.random() < 0.5 ? -1 : 1) * (3 + Math.random() * 6);
        var to = landingSpot(rot);

        // Read back a layout value so the browser cannot fold the two writes
        // into one and skip the transition entirely.
        void el.offsetWidth;
        el.classList.add('is-dealing');
        el.style.width = '';
        place(el, to.x, to.y, rot);
        el.addEventListener('transitionend', function done(e) {
            if (e.propertyName !== 'transform') return;
            el.classList.remove('is-dealing');
            el.removeEventListener('transitionend', done);
        });

        makePlayable(el);
        addExpand(el);

        // The gap closes immediately, from the front of the rack. Once the rack
        // is empty there is nothing to close it with and the hand simply gets
        // shorter - which is what eventually ends the round.
        var added = draw(true);
        layOutFan();
        if (added) {
            // A frame with the card laid out but still offset, so removing the
            // class has somewhere to animate from. Without the reflow the two
            // writes fold into one and it simply appears.
            void added.offsetWidth;
            requestAnimationFrame(function () { added.classList.remove('is-entering'); });
        }

        updateCount();
        // Nothing in hand and nothing to come: the round is over.
        if (!hand.length && !rack.length) setTimeout(runReset, 620);
    }

    /* ---------------- a card on the table ---------------- */

    function makePlayable(el) {
        var drag = null;
        // Set when a gesture turned out to be a drag, so the click that follows
        // it does not also flip the card over.
        var swallowClick = false;

        el.addEventListener('pointerdown', function (e) {
            if (e.button !== undefined && e.button !== 0) return;
            el.style.zIndex = String(++topZ);
            drag = {
                id: e.pointerId,
                px: e.clientX, py: e.clientY,
                ox: readVar(el, '--x'), oy: readVar(el, '--y'),
                moved: false,
            };
            // Capture, so a fast drag that outruns the pointer keeps sending
            // moves here instead of to whatever is now underneath it.
            if (el.setPointerCapture) el.setPointerCapture(e.pointerId);
        });

        // Belt to the images' braces: a card is a <button> holding pictures,
        // and anything in it that the browser decides is draggable would take
        // the gesture away from the handlers below.
        el.addEventListener('dragstart', function (e) { e.preventDefault(); });

        el.addEventListener('pointermove', function (e) {
            if (!drag || e.pointerId !== drag.id) return;
            var dx = e.clientX - drag.px, dy = e.clientY - drag.py;
            if (!drag.moved && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
            if (!drag.moved) {
                drag.moved = true;
                // Bounds for this card's own tilt — #felt clips, and the corner
                // of a tilted card reaches further than its upright box does —
                // measured once, here, the way lift() measures the rack's
                // slots. Nothing in this gesture moves the surface or changes
                // the card's tilt, and bounds() reads the surface's box and
                // --card-w-played off the computed style: five forced
                // style-and-layout passes on a handler that then writes to the
                // same element, every move. Read before the class and the tilt
                // below dirty the style it would have to be recomputed from.
                drag.bounds = bounds(readVar(el, '--rot'));
                // The flight, if it is still running, would fight the drag.
                el.classList.remove('is-dealing');
                el.classList.add('is-dragging');
                // The card is the one thing on this page that moves without a
                // compositor layer of its own: #surface has translate3d and is
                // promoted, so panning the whole table is nearly free, while a
                // card being dragged is repainted into the table's layer every
                // frame. That means re-rastering the band it has swept through,
                // and rastering that band means decoding again every animated
                // work inside it — which is why the further the card goes the
                // worse it gets. One long drag across a table of ten cards cost
                // 677ms of image decoding and dropped seventeen frames; on its
                // own layer the same drag costs 24ms and drops three. Only for
                // the gesture: a layer per card kept for the life of the page
                // is the other way to spend that, and a table fills up.
                el.style.willChange = 'transform';
                // Four degrees, leaning the way the card is being pulled. Set
                // once, at the moment the gesture becomes a drag, rather than
                // tracked live: the tilt is a signal that the card has been
                // picked up, and one that wobbled as you moved would be noise.
                el.style.setProperty('--tilt', (dx >= 0 ? 4 : -4) + 'deg');
            }
            var b = drag.bounds;
            var x = Math.min(Math.max(drag.ox + dx, b.minX), b.maxX);
            var y = Math.min(Math.max(drag.oy + dy, b.minY), b.maxY);
            el.style.setProperty('--x', x + 'px');
            el.style.setProperty('--y', y + 'px');
        });

        function end(e) {
            if (!drag || e.pointerId !== drag.id) return;
            if (el.releasePointerCapture && el.hasPointerCapture && el.hasPointerCapture(e.pointerId)) {
                el.releasePointerCapture(e.pointerId);
            }
            el.classList.remove('is-dragging');
            el.style.removeProperty('--tilt');
            // Off the compositor again. The layer was worth its memory while
            // the card was moving and is worth nothing now it has stopped.
            el.style.willChange = '';
            swallowClick = drag.moved;
            drag = null;
        }
        el.addEventListener('pointerup', end);
        el.addEventListener('pointercancel', end);

        // Flipping is bound to click rather than to pointerup so that Enter and
        // Space on a focused card turn it over too.
        el.addEventListener('click', function () {
            if (swallowClick) { swallowClick = false; return; }
            toggleFlip(el);
        });
    }

    /* ---------------- the card, opened ---------------- */

    /* A card's expand control puts it in a modal, larger, over a blurred page.
       The card in there is built fresh on every open and thrown away on close:
       there is then never a second copy of a work sitting in the document, and
       the rise always has a new element to play on. */

    var modalEl = document.getElementById('card-modal');
    var modalPanel = modalEl && modalEl.querySelector('[role="dialog"]');
    var modalCardEl = document.getElementById('modal-card');
    var modalOpener = null;

    function modalFocusable() {
        var all = modalEl.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
        return Array.prototype.filter.call(all, function (el) {
            return !el.disabled && el.getClientRects().length > 0;
        });
    }

    function openModal(work, opener) {
        if (!modalEl || !modalCardEl || !work) return;
        modalOpener = opener || null;
        modalCardEl.innerHTML = '';

        var card = buildCard(work, { interactive: true, detail: true });
        card.flipBtn.setAttribute('aria-label', work.title + ' — turn over to read about it');
        card.flipBtn.setAttribute('aria-pressed', 'false');
        card.addEventListener('click', function () { toggleFlip(card); });
        modalCardEl.appendChild(card);

        // The dialog is named after the work it is showing, so it announces
        // something better than "dialog" when it takes focus.
        if (modalPanel) modalPanel.setAttribute('aria-label', work.title);
        modalEl.removeAttribute('hidden');
        // On <body>, which propagates to the viewport, so the scrollbar goes
        // with it and the scrim measures exactly the window.
        document.body.classList.add('modal-open');

        // There is no close button to take focus, so it goes to the card
        // itself - which is the one thing in here you can do anything with,
        // and announces what turning it over will give you.
        if (card.flipBtn) card.flipBtn.focus();
    }

    function closeModal() {
        if (!modalEl || modalEl.hasAttribute('hidden')) return;
        modalEl.setAttribute('hidden', '');
        document.body.classList.remove('modal-open');
        modalCardEl.innerHTML = '';
        // Back to the control that opened it, or focus is left on nothing and
        // the next Tab starts from the top of the page.
        if (modalOpener && document.contains(modalOpener)) modalOpener.focus();
        modalOpener = null;
    }

    if (modalEl) {
        // Anywhere but the card closes it. Written as "not on the card" rather
        // than as a listener on the scrim: the panel is taller than the card it
        // holds, so a click in the space beside or below one would otherwise
        // land on the panel and do nothing, which reads as the page having
        // ignored you.
        modalEl.addEventListener('click', function (e) {
            if (!modalCardEl.contains(e.target)) closeModal();
        });

        document.addEventListener('keydown', function (e) {
            if (modalEl.hasAttribute('hidden')) return;
            if (e.key === 'Escape') { closeModal(); return; }
            if (e.key !== 'Tab') return;
            // Tab must not walk out of the modal and start operating the page
            // that is blurred behind it. Only the two ends are handled; in
            // between, the browser's own order is the right one.
            var f = modalFocusable();
            if (!f.length) { e.preventDefault(); return; }
            var i = f.indexOf(document.activeElement);
            var next = e.shiftKey ? i - 1 : i + 1;
            if (i === -1 || next < 0 || next >= f.length) {
                e.preventDefault();
                f[e.shiftKey ? f.length - 1 : 0].focus();
            }
        });
    }

    /* ---------------- the catalogue ---------------- */

    // The slots are made once and kept for the life of the page. Cards move
    // between them; the slots themselves never come or go, so the block holds
    // its footprint and the empties collect at the end rather than the whole
    // grid reflowing shorter every time a card is played.
    //
    // There is one slot per work still to come, which is the whole sketchbook
    // less the hand: a round opens by dealing HAND cards off the front of the
    // rack, and nothing ever puts a card back, so the rack peaks at
    // works.length - HAND on the first frame of a round and only falls from
    // there. Building works.length of them left the last five standing empty
    // for the life of the page, reading as five cards that had been played
    // before the page loaded.
    function buildGrid() {
        var frag = document.createDocumentFragment();
        slotEls = [];
        for (var i = 0; i < works.length - HAND; i++) {
            var slot = document.createElement('div');
            slot.className = 'slot';
            slotEls.push(slot);
            frag.appendChild(slot);
        }
        gridEl.appendChild(frag);
        deal(null);
    }

    // Opens a round: the rack is the whole pack, shuffled, and the hand is
    // taken off the top of it before the rack is drawn - so the rack renders
    // holding exactly what is still to come, with the slots the hand is
    // holding already standing empty at the end. `from` deals the rack in from
    // a point instead of simply putting it there.
    function deal(from) {
        while (fanEl.firstChild) fanEl.removeChild(fanEl.firstChild);
        hand = [];
        rack = shuffle(works);
        var opening = rack.splice(0, HAND);
        for (var i = 0; i < opening.length; i++) addToHand(opening[i], false);
        layOutFan();
        fillRack(from);
        updateCount();
    }

    // Fills the rack from `rack`, one card per slot from the front. With `from`
    // - a point in client coordinates - every card starts there instead, face
    // down and the size it was on the table, and flies home turning over.
    function fillRack(from) {
        // A card being carried belongs to a rack that is about to stop
        // existing. It is pinned over #grid rather than sitting in a slot, so
        // emptying the slots below would leave it behind on the page.
        abandonCarry();
        for (var i = 0; i < slotEls.length; i++) {
            while (slotEls[i].firstChild) slotEls[i].removeChild(slotEls[i].firstChild);
        }
        tileOf = {};
        var list = [];
        for (var i = 0; i < rack.length; i++) {
            var card = buildCard(rack[i], { still: true, back: true });
            slotEls[i].appendChild(card);
            tileOf[rack[i].id] = card;
            makeSortable(card, rack[i]);
            // A tile is a card you have not played yet, and wanting to read
            // about one before you decide to play it is the obvious thing to
            // want. Same control, same corner, same modal - it appears on
            // hover exactly as it does on the table, and its pointerdown is
            // stopped inside addExpand, so reaching for it never starts the
            // drag that would reorder the rack.
            addExpand(card);
            list.push(card);
        }
        labelRack();
        if (!from) return;

        // Every rect read before any transform is written. One card's transform
        // cannot move another, but keeping the reads and the writes apart is
        // what stops a loop like this thrashing layout.
        var rects = list.map(function (c) { return c.getBoundingClientRect(); });
        list.forEach(function (c, i) {
            var r = rects[i];
            c.classList.add('is-flipped');
            c.style.transition = 'none';
            c.style.transform = 'translate('
                + (from.x - (r.left + r.width / 2)) + 'px,'
                + (from.y - (r.top + r.height / 2)) + 'px) scale('
                + (r.width ? playedW() / r.width : 0.5) + ')';
        });
        void gridEl.offsetWidth;
        list.forEach(function (c, i) {
            var at = i * DEAL_STEP_MS;
            setTimeout(function () {
                c.classList.add('is-moving');
                c.style.transition = '';
                c.style.transform = '';
            }, at);
            // The turn starts as the card lands, so the rack comes up face by
            // face rather than all at once at the end.
            setTimeout(function () { c.classList.remove('is-flipped'); }, at + 380);
            setTimeout(function () { c.classList.remove('is-moving'); }, at + 900);
        });
    }

    // Everything you can still do something with - the cards in your hand and
    // the cards still to come - out of what the sketchbook has. A card played
    // onto the table has left both, so the number only ever falls until the
    // round is reshuffled.
    function updateCount() {
        if (countEl) countEl.textContent = '(' + (hand.length + rack.length) + '/' + works.length + ')';
    }

    // Takes the work at `idx` out of the rack and hands it back, closing the
    // rack up behind it. This is the one way a card leaves the rack, whether it
    // is being drawn into your hand or the round is ending, so there is a
    // single place where `rack`, `tileOf` and the slots are kept in step.
    function takeFromRack(idx) {
        // A card in the air is put down before anything is spliced out from
        // under it. The rack can be dragged with one finger while the other
        // plays a card off the hand, and the splice below indexes `rack`
        // against the slots — which only agree once the carried card has landed.
        dropCarry(false);
        if (idx < 0 || idx >= rack.length) return null;
        var work = rack[idx];

        // First: where every card that is staying sits right now.
        var stay = [];
        for (var i = idx + 1; i < rack.length; i++) {
            var c = tileOf[rack[i].id];
            if (c) stay.push({ el: c, r: c.getBoundingClientRect() });
        }

        var leaving = tileOf[work.id];
        rack.splice(idx, 1);
        delete tileOf[work.id];

        // The one that has gone shrinks where it stood. It is lifted out of its
        // slot and pinned over the grid first, so the slot is already free for
        // the card advancing into it while this one is still on screen.
        if (leaving) {
            var lr = leaving.getBoundingClientRect();
            var gr = gridEl.getBoundingClientRect();
            gridEl.appendChild(leaving);
            leaving.style.left = (lr.left - gr.left) + 'px';
            leaving.style.top = (lr.top - gr.top) + 'px';
            leaving.style.width = lr.width + 'px';
            leaving.style.height = lr.height + 'px';
            void leaving.offsetWidth;
            leaving.classList.add('is-leaving');
            setTimeout(function () {
                if (leaving.parentNode) leaving.parentNode.removeChild(leaving);
            }, 360);
        }

        // Last: everything behind it moves up a slot.
        for (var i = idx; i < rack.length; i++) slotEls[i].appendChild(tileOf[rack[i].id]);

        // Invert, then play.
        for (var i = 0; i < stay.length; i++) {
            var now = stay[i].el.getBoundingClientRect();
            var dx = stay[i].r.left - now.left, dy = stay[i].r.top - now.top;
            if (!dx && !dy) continue;
            stay[i].el.classList.remove('is-moving');
            stay[i].el.style.transform = 'translate(' + dx + 'px,' + dy + 'px)';
        }
        void gridEl.offsetWidth;
        for (var i = 0; i < stay.length; i++) {
            stay[i].el.classList.add('is-moving');
            stay[i].el.style.transform = '';
        }

        updateCount();
        labelRack();
        return work;
    }

    /* ---------------- reordering the rack ---------------- */

    /* The upcoming cards are a running order, not a fixed list, so one can be
       picked up and dropped into another slot. The slots themselves still never
       move — only which card is in which — so this is takeFromRack()'s FLIP
       again, driven by a pointer instead of by a draw.

       The order is not decoration: the hand draws off the front of the rack, so
       dragging a card forward is how you choose what you get next. */

    // The card being carried, or null. Kept at this scope rather than inside
    // makeSortable() so that anything rebuilding the rack underneath a drag —
    // a play, a reshuffle — can put it down first.
    var carry = null;

    var rackStatus = document.getElementById('rack-status');

    function rackIndex(work) {
        for (var i = 0; i < rack.length; i++) if (rack[i].id === work.id) return i;
        return -1;
    }

    // `rack` with the card at `from` taken out and put back in at `to`. A
    // splice and not a swap: the cards in between shift by one, which is what
    // keeps the rack packed from the front rather than leaving a hole in the
    // middle with cards behind it.
    function orderWith(from, to) {
        var next = rack.slice();
        next.splice(to, 0, next.splice(from, 1)[0]);
        return next;
    }

    // Position is part of a tile's name. A reorder is otherwise invisible to a
    // reader who is not looking at the grid, and the keyboard path below is
    // nothing but a run of them.
    function labelRack() {
        for (var i = 0; i < rack.length; i++) {
            var c = tileOf[rack[i].id];
            if (!c) continue;
            c.setAttribute('aria-label',
                rack[i].title + ', ' + (i + 1) + ' of ' + rack.length + ' upcoming');
        }
    }

    function announce(msg) { if (rackStatus) rackStatus.textContent = msg; }

    // How many cards a row of the rack holds. Read off the grid rather than
    // written down: the column count steps from five to three to two on the way
    // to a phone, and this would be the fourth place that number lived.
    function columns() {
        var t = getComputedStyle(gridEl).gridTemplateColumns;
        return Math.max(1, t ? t.trim().split(/\s+/).length : 1);
    }

    // Puts `list` into the slots from the front and animates everything that
    // had to move. `held` is a work whose card is in the air: its slot is left
    // empty for it, and that gap is the preview of where the drop lands.
    function layOutRack(list, held) {
        var movers = [];
        // First: every rect read before a single card is touched.
        for (var i = 0; i < list.length; i++) {
            var c = tileOf[list[i].id];
            if (!c || (held && list[i].id === held.id)) continue;
            movers.push({ el: c, at: i, r: c.getBoundingClientRect() });
        }

        // Last. Every card comes out of its slot before any goes back in: a
        // card here can move either way along the rack, so appending into a
        // slot that has not been emptied yet leaves two cards stacked in it and
        // one slot showing the :empty hairline. takeFromRack() gets away without
        // the first pass because everything there only ever moves towards the
        // front, into a slot vacated a moment earlier.
        for (var i = 0; i < movers.length; i++) {
            if (movers[i].el.parentNode) movers[i].el.parentNode.removeChild(movers[i].el);
        }
        for (var i = 0; i < movers.length; i++) slotEls[movers[i].at].appendChild(movers[i].el);

        // Invert.
        for (var i = 0; i < movers.length; i++) {
            var now = movers[i].el.getBoundingClientRect();
            var dx = movers[i].r.left - now.left, dy = movers[i].r.top - now.top;
            if (!dx && !dy) continue;
            // The transition comes off first. A card caught mid-slide was
            // measured where it is on screen, and the offset has to be taken up
            // in one step rather than animated to.
            movers[i].el.classList.remove('is-moving');
            movers[i].el.style.transform = 'translate(' + dx + 'px,' + dy + 'px)';
        }
        void gridEl.offsetWidth;
        // Play.
        for (var i = 0; i < movers.length; i++) {
            movers[i].el.classList.add('is-moving');
            movers[i].el.style.transform = '';
        }
    }

    // One move, committed: the model, the slots and the labels in step.
    function moveCard(work, to) {
        var from = rackIndex(work);
        if (from === -1) return false;
        to = Math.min(Math.max(to, 0), rack.length - 1);
        if (to === from) return false;
        rack = orderWith(from, to);
        layOutRack(rack, null);
        labelRack();
        announce(work.title + ' moved to position ' + (to + 1) + ' of ' + rack.length);
        return true;
    }

    // Which slot the card in the air is over. The nearest slot centre rather
    // than whatever is under the pointer: the gutters between slots are dead
    // space, and a drop that did nothing because a finger was in one would read
    // as the page having missed the gesture.
    function slotUnder(cx, cy) {
        var best = 0, bestD = Infinity;
        for (var i = 0; i < carry.boxes.length; i++) {
            var dx = carry.boxes[i].cx - cx, dy = carry.boxes[i].cy - cy;
            var d = dx * dx + dy * dy;
            if (d < bestD) { bestD = d; best = i; }
        }
        return best;
    }

    // Puts the carried card down where the gap is. `animate` is false when
    // something else needs the rack this instant; either way the model and the
    // DOM come back into step before this returns.
    function dropCarry(animate) {
        if (!carry) return;
        var c = carry;
        carry = null;
        if (c.el.releasePointerCapture && c.el.hasPointerCapture && c.el.hasPointerCapture(c.id)) {
            c.el.releasePointerCapture(c.id);
        }
        // A press that never cleared the slop never left its slot, so there is
        // nothing to put back.
        if (!c.lifted) return;

        var was = c.el.getBoundingClientRect();
        rack = orderWith(c.from, c.to);
        c.el.classList.remove('is-lifted');
        c.el.style.left = '';
        c.el.style.top = '';
        c.el.style.width = '';
        c.el.style.height = '';
        c.el.style.transform = '';
        slotEls[c.to].appendChild(c.el);

        // The same FLIP the other cards get, so the card settles into the slot
        // from wherever it was let go of instead of snapping into it.
        if (animate) {
            var now = c.el.getBoundingClientRect();
            var dx = was.left - now.left, dy = was.top - now.top;
            if (dx || dy) {
                c.el.style.transform = 'translate(' + dx + 'px,' + dy + 'px)';
                void gridEl.offsetWidth;
                c.el.classList.add('is-moving');
                c.el.style.transform = '';
            }
        }
        labelRack();
        if (c.to !== c.from) {
            announce(c.work.title + ' moved to position ' + (c.to + 1) + ' of ' + rack.length);
        }
    }

    // The rack is being rebuilt from scratch, so there is no order left to
    // commit the carried card into — it is simply taken off the page.
    function abandonCarry() {
        if (!carry) return;
        var c = carry;
        carry = null;
        if (c.el.releasePointerCapture && c.el.hasPointerCapture && c.el.hasPointerCapture(c.id)) {
            c.el.releasePointerCapture(c.id);
        }
        if (c.el.parentNode === gridEl) gridEl.removeChild(c.el);
    }

    function makeSortable(el, work) {
        // A tile was a picture in a box; it is now something you can move, so
        // it has to be reachable without a pointer as well as with one.
        el.tabIndex = 0;
        el.setAttribute('aria-describedby', 'rack-help');

        // Belt to the images' braces, the same as a card on the table: pressing
        // on a picture and moving hands the gesture to the browser's own
        // drag-and-drop, and the pointer events simply stop arriving.
        el.addEventListener('dragstart', function (e) { e.preventDefault(); });

        el.addEventListener('pointerdown', function (e) {
            if (e.button !== undefined && e.button !== 0) return;
            // Not while the pack is coming together and going back out: every
            // card in the rack is about to be replaced.
            if (resetting || carry) return;
            if (rackIndex(work) === -1) return;
            carry = {
                el: el, work: work, id: e.pointerId,
                px: e.clientX, py: e.clientY,
                from: rackIndex(work), to: rackIndex(work),
                lifted: false, boxes: null, pin: null,
            };
            // Capture, so a drag that outruns the pointer keeps sending moves
            // here rather than to whichever tile is now underneath it.
            if (el.setPointerCapture) el.setPointerCapture(e.pointerId);
        });

        // Out of its slot and pinned over #grid, which is already positioned
        // for the card takeFromRack() flies out. Lifting frees the slot, so the card
        // shifting into it has somewhere to go while this one is still in hand.
        function lift() {
            carry.lifted = true;
            var r = el.getBoundingClientRect();
            var gr = gridEl.getBoundingClientRect();
            // Every slot measured once, here. Slots are fixed for the life of
            // the page and nothing in this gesture moves them, which keeps the
            // move handler off the layout entirely.
            carry.boxes = [];
            for (var i = 0; i < rack.length; i++) {
                var s = slotEls[i].getBoundingClientRect();
                carry.boxes.push({
                    cx: s.left - gr.left + s.width / 2,
                    cy: s.top - gr.top + s.height / 2,
                });
            }
            carry.pin = {
                cx: r.left - gr.left + r.width / 2,
                cy: r.top - gr.top + r.height / 2,
            };
            // Any transition still running would fight the pointer.
            el.classList.remove('is-moving');
            el.style.transform = '';
            gridEl.appendChild(el);
            el.classList.add('is-lifted');
            el.style.left = (r.left - gr.left) + 'px';
            el.style.top = (r.top - gr.top) + 'px';
            el.style.width = r.width + 'px';
            el.style.height = r.height + 'px';
        }

        el.addEventListener('pointermove', function (e) {
            if (!carry || carry.el !== el || e.pointerId !== carry.id) return;
            if (resetting) { abandonCarry(); return; }
            var dx = e.clientX - carry.px, dy = e.clientY - carry.py;
            // The same few pixels makePlayable() allows. A rack that threw a
            // tile out of its slot every time the page was touched would be
            // unusable on a phone, and unreadable with a mouse.
            if (!carry.lifted && Math.abs(dx) + Math.abs(dy) < DRAG_SLOP) return;
            if (!carry.lifted) lift();
            el.style.transform = 'translate(' + dx + 'px,' + dy + 'px)';

            var to = slotUnder(carry.pin.cx + dx, carry.pin.cy + dy);
            if (to === carry.to) return;
            carry.to = to;
            // The preview is the drop. What opens up under the card is exactly
            // where it lands if it is let go of here.
            layOutRack(orderWith(carry.from, to), carry.work);
        });

        function endDrag(e) {
            if (!carry || carry.el !== el || e.pointerId !== carry.id) return;
            dropCarry(true);
        }
        el.addEventListener('pointerup', endDrag);
        el.addEventListener('pointercancel', endDrag);

        // The same reorder without a pointer. Left and right step one slot; up
        // and down step a row, whatever a row is at this width.
        el.addEventListener('keydown', function (e) {
            if (resetting || carry) return;
            var step = 0;
            if (e.key === 'ArrowRight') step = 1;
            else if (e.key === 'ArrowLeft') step = -1;
            else if (e.key === 'ArrowDown') step = columns();
            else if (e.key === 'ArrowUp') step = -columns();
            else return;
            e.preventDefault();
            var from = rackIndex(work);
            if (from === -1) return;
            if (!moveCard(work, from + step)) return;
            // layOutRack() takes the tile out of the document to put it in its
            // new slot, and focus does not survive that — so it is put back,
            // and without the scroll that focus() would otherwise do on a page
            // whose scrolling is smooth site-wide.
            el.focus({ preventScroll: true });
        });
    }

    /* ---------------- the end of a round ---------------- */

    // Where the pack comes together: the middle of the part of the table you
    // can see, above the hand, in surface coordinates.
    function stackSpot() {
        var f = felt.getBoundingClientRect();
        var sr = surface.getBoundingClientRect();
        var top = f.top - sr.top;
        var fanTop = fanEl.getBoundingClientRect().top - sr.top;
        return {
            x: (f.left - sr.left) + (f.width - playedW()) / 2,
            y: top + Math.max(10, (fanTop - top - playedH()) / 2),
        };
    }

    // Every card in play comes together, three of them riffle, and the whole
    // pack goes back out into the rack face down, turning over one by one.
    function runReset() {
        if (resetting) return;
        resetting = true;

        var cards = Array.prototype.slice.call(playedEl.children);
        // One card's shadow is depth; twenty-one of them squared up on the
        // same spot is a dark smudge under the pack, because each card casts
        // over the one below instead of the table. The pile keeps its hairline
        // edge, which is what makes it read as paper at all.
        playedEl.classList.add('is-shuffling');
        var spot = stackSpot();
        var sr = surface.getBoundingClientRect();
        // Held in client coordinates for the deal, which happens after the
        // table has been cleared and there is nothing left to measure from.
        var from = { x: sr.left + spot.x + playedW() / 2, y: sr.top + spot.y + playedH() / 2 };

        cards.forEach(function (c, i) {
            c.classList.remove('is-dealing');
            c.classList.add('is-gathering');
            c.style.zIndex = String(1000 + i);
            // A pack squares up, but not perfectly - a pixel or two of slop is
            // what makes it read as paper rather than as one thick card.
            place(c, spot.x + (i % 3) - 1, spot.y + (i % 2), 0);
        });

        var round = 0;
        var three = cards.slice(-3);

        function riffle() {
            if (!three.length) { redeal(); return; }
            three.forEach(function (c, i) {
                c.classList.remove('is-gathering');
                c.classList.add('is-riffling');
                place(c, spot.x + (i - 1) * playedW() * 0.66, spot.y - 8 + i * 3, (i - 1) * 8);
            });
            setTimeout(function () {
                three.forEach(function (c, i) { place(c, spot.x + (i % 3) - 1, spot.y + (i % 2), 0); });
                round++;
                setTimeout(round < 3 ? riffle : redeal, RIFFLE_MS);
            }, RIFFLE_MS);
        }

        function redeal() {
            playedEl.classList.remove('is-shuffling');
            while (playedEl.firstChild) playedEl.removeChild(playedEl.firstChild);
            deal(from);
            resetting = false;
        }

        setTimeout(riffle, cards.length ? GATHER_MS : 0);
    }

    /* ---------------- start ---------------- */

    fetch(MANIFEST)
        .then(function (r) {
            if (!r.ok) throw new Error('works.json: HTTP ' + r.status);
            return r.json();
        })
        .then(function (data) {
            works = (data && data.works) || [];
            if (!works.length) throw new Error('works.json held no works');
            // buildGrid deals the opening round: the rack, and the hand off
            // the top of it.
            buildGrid();
            centrePan();
        })
        .catch(function (err) {
            // The catalogue is the page; without it there is nothing to show,
            // and an empty grid with a heading counting to zero would read as a
            // sketchbook with nothing in it rather than as a page that failed.
            if (emptyEl) emptyEl.hidden = false;
            if (countEl) countEl.textContent = '';
            console.error('[sketchbook]', err);
        });

    // The fan is placed in pixels off its own measured width, so a resize that
    // crosses the breakpoint has to re-lay it out.
    var resizeTimer = null;
    window.addEventListener('resize', function () {
        clearTimeout(resizeTimer);
        resizeTimer = setTimeout(function () {
            layOutFan();
            // The surface is sized in percentages, so its limits move with the
            // window and a pan that was legal a moment ago may not be.
            applyPan();
        }, 120);
    });
})();
